//
// EmailTemplateData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Contains the data of the email template, including the subject and body in HTML and plaintext variants */
public struct EmailTemplateData: Codable, JSONEncodable, Hashable {

    public var body: EmailTemplateDataBody
    public var subject: String

    public init(body: EmailTemplateDataBody, subject: String) {
        self.body = body
        self.subject = subject
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case body
        case subject
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(body, forKey: .body)
        try container.encode(subject, forKey: .subject)
    }
}

