//
// GetOrganizationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetOrganizationResponse: Codable, JSONEncodable, Hashable {

    public var organization: Organization

    public init(organization: Organization) {
        self.organization = organization
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case organization
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(organization, forKey: .organization)
    }
}

