//
// IdentityCredentialsCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** CredentialsCode represents a one time login/registration code */
public struct IdentityCredentialsCode: Codable, JSONEncodable, Hashable {

    public var addressType: String?
    public var usedAt: Date?

    public init(addressType: String? = nil, usedAt: Date? = nil) {
        self.addressType = addressType
        self.usedAt = usedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case addressType = "address_type"
        case usedAt = "used_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(addressType, forKey: .addressType)
        try container.encodeIfPresent(usedAt, forKey: .usedAt)
    }
}

