//
// LoginFlowState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The state represents the state of the login flow.  choose_method: ask the user to choose a method (e.g. login account via email) sent_email: the email has been sent to the user passed_challenge: the request was successful and the login challenge was passed. */
public enum LoginFlowState: String, Codable, CaseIterable {
    case chooseMethod = "choose_method"
    case sentEmail = "sent_email"
    case passedChallenge = "passed_challenge"
}
