//
// Organization.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** B2B SSO Organization */
public struct Organization: Codable, JSONEncodable, Hashable {

    /** The organization's creation date. */
    public var createdAt: Date
    public var domains: [String]
    /** The organization's ID. */
    public var id: String
    /** The organization's human-readable label. */
    public var label: String
    /** The project's ID. */
    public var projectId: String
    /** The last time the organization was updated. */
    public var updatedAt: Date

    public init(createdAt: Date, domains: [String], id: String, label: String, projectId: String, updatedAt: Date) {
        self.createdAt = createdAt
        self.domains = domains
        self.id = id
        self.label = label
        self.projectId = projectId
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt = "created_at"
        case domains
        case id
        case label
        case projectId = "project_id"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(domains, forKey: .domains)
        try container.encode(id, forKey: .id)
        try container.encode(label, forKey: .label)
        try container.encode(projectId, forKey: .projectId)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

