//
// Project.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Project: Codable, JSONEncodable, Hashable {

    public enum State: String, Codable, CaseIterable {
        case running = "running"
        case halted = "halted"
        case deleted = "deleted"
    }
    public var corsAdmin: ProjectCors
    public var corsPublic: ProjectCors
    /** The project's ID. */
    public var id: String
    /** The name of the project. */
    public var name: String
    /** The configuration revision ID. */
    public var revisionId: String
    public var services: ProjectServices
    /** The project's slug */
    public var slug: String
    /** The state of the project. running Running halted Halted deleted Deleted */
    public var state: State

    public init(corsAdmin: ProjectCors, corsPublic: ProjectCors, id: String, name: String, revisionId: String, services: ProjectServices, slug: String, state: State) {
        self.corsAdmin = corsAdmin
        self.corsPublic = corsPublic
        self.id = id
        self.name = name
        self.revisionId = revisionId
        self.services = services
        self.slug = slug
        self.state = state
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case corsAdmin = "cors_admin"
        case corsPublic = "cors_public"
        case id
        case name
        case revisionId = "revision_id"
        case services
        case slug
        case state
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(corsAdmin, forKey: .corsAdmin)
        try container.encode(corsPublic, forKey: .corsPublic)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(revisionId, forKey: .revisionId)
        try container.encode(services, forKey: .services)
        try container.encode(slug, forKey: .slug)
        try container.encode(state, forKey: .state)
    }
}

