//
// RegistrationFlowState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** choose_method: ask the user to choose a method (e.g. registration with email) sent_email: the email has been sent to the user passed_challenge: the request was successful and the registration challenge was passed. */
public enum RegistrationFlowState: String, Codable, CaseIterable {
    case chooseMethod = "choose_method"
    case sentEmail = "sent_email"
    case passedChallenge = "passed_challenge"
}
