//
// SetProject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SetProject: Codable, JSONEncodable, Hashable {

    public var corsAdmin: ProjectCors
    public var corsPublic: ProjectCors
    /** The name of the project. */
    public var name: String
    public var services: ProjectServices

    public init(corsAdmin: ProjectCors, corsPublic: ProjectCors, name: String, services: ProjectServices) {
        self.corsAdmin = corsAdmin
        self.corsPublic = corsPublic
        self.name = name
        self.services = services
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case corsAdmin = "cors_admin"
        case corsPublic = "cors_public"
        case name
        case services
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(corsAdmin, forKey: .corsAdmin)
        try container.encode(corsPublic, forKey: .corsPublic)
        try container.encode(name, forKey: .name)
        try container.encode(services, forKey: .services)
    }
}

