//
// UpdateLoginFlowWithCodeMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Update Login flow using the code method */
public struct UpdateLoginFlowWithCodeMethod: Codable, JSONEncodable, Hashable {

    /** Code is the 6 digits code sent to the user */
    public var code: String?
    /** CSRFToken is the anti-CSRF token */
    public var csrfToken: String
    /** Identifier is the code identifier The identifier requires that the user has already completed the registration or settings with code flow. */
    public var identifier: String?
    /** Method should be set to \"code\" when logging in using the code strategy. */
    public var method: String
    /** Resend is set when the user wants to resend the code */
    public var resend: String?

    public init(code: String? = nil, csrfToken: String, identifier: String? = nil, method: String, resend: String? = nil) {
        self.code = code
        self.csrfToken = csrfToken
        self.identifier = identifier
        self.method = method
        self.resend = resend
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case csrfToken = "csrf_token"
        case identifier
        case method
        case resend
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encode(csrfToken, forKey: .csrfToken)
        try container.encodeIfPresent(identifier, forKey: .identifier)
        try container.encode(method, forKey: .method)
        try container.encodeIfPresent(resend, forKey: .resend)
    }
}

